// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>NextJS Dasar</title>
      </head>
      <body>
        {/* <div>
          <h1>Navbar</h1>
        </div> */}
        {children}
        {/* <div>
          <h1>Footer</h1>
        </div> */}
      </body>
    </html>
  )
}
